repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-quotes']
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python ./run_in_venv.py pylint  # Since PyCharm will not execute git hooks in virtualenv.
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: python ./run_in_venv.py pytest  # Since PyCharm will not execute git hooks in virtualenv.
        language: system
        always_run: true
        pass_filenames: false
